version: '3.9'
services: 
  app: 
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"